services:
  redis:
    image: redis:8.2.3-alpine
    expose:
      - "6379"
    volumes:
      - ./redis_data:/data
    networks:
      - universal_tracker

  tracker:
    build:
      context: .
      dockerfile: tracker.Dockerfile
    ports:
      - "8070:80"
    networks:
      - universal_tracker
    depends_on:
      - redis

  broadcaster:
    build:
      context: .
      dockerfile: broadcaster.Dockerfile
    expose:
      - "80"
    networks:
      - universal_tracker
    depends_on:
      - redis

  target:
    image: atdr.meo.ws/fusl/ateam-airsync:latest
    environment:
      - MAX_CONN=18
      - PORT=873
      - DISK_LIMIT=50
      - DISK_HARD_LIMIT=80
    expose:
      - "873"
    volumes:
      - ./target_data:/data
    networks:
      - universal_tracker
    depends_on:
      - redis

  # grab:
  #   image: <your-grab-image:latest>
  #   container_name: <your-grab-container-name>
  #   entrypoint: ["run-pipeline3", "--disable-web-server", "pipeline.py", "--concurrent", "<concurrency between 1 and 20 (both numbers inclusive)>", "<your nickname to appear on the tracker>"]
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: 50m
  #   restart: unless-stopped
  #   networks:
  #     - universal_tracker
  #   depends_on:
  #     - tracker
  #     - target

networks:
  universal_tracker: {}
